### ISSUE TITLE
Not working with TeamCity 10

### ISSUE THREAD

**Issue by dguder** [anisimovsergey/teamcity-gadget#1]
With Teamcity 10 only projects and no build configuration where shown.

The parser for page at /win32/userStatus.html needs to be updated. Some `<img>` tags where changed to `<span>` tags.

**Comment by dguder** [comment]
I fixed the general tag rename and added a few new states to the html parser. I fixed not all states.  
Please check it out at   dguder/teamcity-gadget@36a853b

**Comment by anisimovsergey** [comment]
Looks, good. Thank you!

**Comment by dguder** [comment]
Should I create a pull request with these changes?

**Comment by anisimovsergey** [comment]
Sure, please do!
